services:
  api:
    build: 
      context: ./api
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - ./api:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - PORT=8080
      - DATABASE_URL=mysql://root:mysqlpassword@db:3306/tfa
      - AUTH_RELYING_PARTY_NAME=TFA Login Example
      - AUTH_RELYING_PARTY_ID=localhost
      - AUTH_RELYING_PARTY_ORIGIN=http://localhost:5173
      - AUTH_TOKEN_ISSUER=two-factor-login
      - AUTH_TOKEN_SECRET=kfdjsu033lkjeluOIUOT#^@$&$%&@ghgdsjagjk
  web:
    build:
      context: ./web
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    depends_on:
      - api
    volumes:
      - ./web:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VITE_API_BASE_URL=http://localhost:8080
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysqlpassword
    ports:
      - "3306:3306"