FROM node:18
RUN apt-get update && apt-get install wait-for-it
WORKDIR /app
COPY package.json yarn.lock ./
RUN yarn install
COPY . .
RUN rm -f /app/.env
EXPOSE 8080
RUN chmod +x ./entrypoint.sh

CMD ["./entrypoint.sh"]